ERROR!
{
	"name": "Error",
	"message": "test error",
	"stack": "Error: test error\n    at /Users/jem/dojo/wayforge/packages/varmint/__tests__/error-interface.test.ts:20:20\n    at Squirrel.write (/Users/jem/dojo/wayforge/packages/varmint/src/squirrel.ts:188:24)\n    at Object.get (/Users/jem/dojo/wayforge/packages/varmint/src/squirrel.ts:244:21)\n    at /Users/jem/dojo/wayforge/packages/varmint/__tests__/error-interface.test.ts:22:53\n    at file:///Users/jem/dojo/wayforge/node_modules/.pnpm/@vitest+runner@3.2.4/node_modules/@vitest/runner/dist/chunk-hooks.js:155:11\n    at file:///Users/jem/dojo/wayforge/node_modules/.pnpm/@vitest+runner@3.2.4/node_modules/@vitest/runner/dist/chunk-hooks.js:752:26\n    at file:///Users/jem/dojo/wayforge/node_modules/.pnpm/@vitest+runner@3.2.4/node_modules/@vitest/runner/dist/chunk-hooks.js:1897:20\n    at new Promise (<anonymous>)\n    at runWithTimeout (file:///Users/jem/dojo/wayforge/node_modules/.pnpm/@vitest+runner@3.2.4/node_modules/@vitest/runner/dist/chunk-hooks.js:1863:10)\n    at runTest (file:///Users/jem/dojo/wayforge/node_modules/.pnpm/@vitest+runner@3.2.4/node_modules/@vitest/runner/dist/chunk-hooks.js:1574:12)",
	"props": {}
}